[workspace]
members=["game", "common"]

[package]
name = "sdl3_gpu"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
sdl3 = "0.15.1"
nalgebra-glm = "0.20.0"
stb_image = "0.3.0"

[dependencies]
common = { path = "./common" }
sdl3 = { workspace = true } 
nalgebra-glm = {workspace = true} 